"""Updated post table to include inmage added inits to tables

Revision ID: 50434a09fb89
Revises: 
Create Date: 2020-11-27 17:05:09.737779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50434a09fb89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image')
    # ### end Alembic commands ###
